### ISSUE TITLE
CORS error on page load after deploying to Walrus Testnet

### ISSUE THREAD

**Issue by kkomelin** [MystenLabs/walrus-sites#276]
### What happened?

Deployed Sui dApp Starter demo to Walrus:
Site object ID: 0xdaf4d7b1631ff366c04d500446342bbcc14023c655cbc6be841c0425d6e7f59e
Browse the resulting site at: https://5gglkxavijbcc4hgtmv772efvqx9vn2urydcny8ob60h38ck9q.walrus.site

### Search terms

for gut sake!

### Steps to reproduce

1. Clone the template https://github.com/new?template_name=sui-dapp-starter&template_owner=suiware&name=my-sui-dapp
2. pnpm i
3. pnpm testnet:start
4. pnpm frontend:deploy:walrus

### Deviation steps

Used Suibase.io for network management

### Relevant log output

```shell
Access to fetch at 'https://aggregator.walrus-testnet.walrus.space/v1/w0BmI4r3iSXOCj2BvhonanH2cudHE81JHeGWnzvwxdM' from origin 'https://5gglkxavijbcc4hgtmv772efvqx9vn2urydcny8ob60h38ck9q.walrus.site' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Version

- [X] `walrus` and `site-builder` are up to date.

### If applicable, what browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by giac-mysten** [comment]
hi @kkomelin , thanks for the report. Just to understand, how do you go from the steps above to deploying onto walrus? I'm not familiar with `pnpm create sui-dapp@0.11.0`.

**Comment by kkomelin** [comment]
Hi @giac-mysten ,
Thanks for reaching back. 
I've updated the description to clarify things a bit better.
I'm using my [suiware/sui-dapp-starter](https://github.com/suiware/sui-dapp-starter) and the [script which I deploy with](The script which I deployed with is here https://github.com/suiware/sui-dapp-starter/blob/main/packages/frontend/scripts/walrus-site-deploy.cjs).

**Comment by giac-mysten** [comment]
hey @kkomelin , sorry i did not reach back to you sooner.
Is the issue still present? I think we may have already solved the root issues on our side.

**Comment by kkomelin** [comment]
Hey @giac-mysten ,
Last week I successfully redeployed to Walrus without any problems, so we can consider this issue addressed.
Thanks for your assistance!
